# -*- coding: utf-8 -*-
"""Imgclassi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CyWOn0KsDTq8Ecvlf9pidh8zO37hTV0Y

### **AMIT ANIL PAWAR**

# **IMAGE CLASSIFIER PROJECT**
"""

!pip install fastai --upgrade --quiet

from fastai.vision.all import *

"""# **Collecting Data**"""

path = Path('data')
path.mkdir(exist_ok=True)

!wget -q https://github.com/pawaramit1423/Image_Scrapper/blob/master/ship.txt
!wget -q https://github.com/pawaramit1423/Image_Scrapper/blob/master/car.txt
!wget -q https://github.com/pawaramit1423/Image_Scrapper/blob/master/bike.txt

download_images('data/ship', Path('ship.txt'))
download_images('data/car', Path('car.txt'))
download_images('data/bike', Path('bike.txt'))

files = get_image_files(path)
len(files)

failed = verify_images(files)
failed

failed.map(Path.unlink) # delete corrupted files

files = get_image_files(path)
len(files)

"""# **DataLoaders**"""

vehicals = DataBlock(
    blocks=(ImageBlock, CategoryBlock), # x,y
    get_items=get_image_files, 
    splitter=RandomSplitter(valid_pct=0.2, seed=25),
    get_y=parent_label,
    item_tfms=RandomResizedCrop(224, min_scale=0.5),
    batch_tfms=aug_transforms())

dls = vehicals.dataloaders(path)

dls.train.show_batch(max_n=9, nrows=3)

"""# **Learner**"""

learn = cnn_learner(dls, resnet18, metrics=error_rate)
learn.fine_tune(3)

learn.predict(files[101])

learn.show_results()

"""# **Inference**"""

interp = ClassificationInterpretation.from_learner(learn)
interp.plot_confusion_matrix()

interp.plot_top_losses(5, nrows=1)

"""# **Deploying Model**"""

learn.export('export.pkl')

!pip install streamlit --quiet
!pip install colab-everything --quiet

!pip install colab_everything

from colab_everything import ColabStreamlit
ColabStreamlit('app.py')